name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-8-jdk
          pip install --user buildozer cython

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@3e5c7e8f92a1fc8947f8ad61b53f08d31bcb8f58
        with:
          name: apk
          path: bin/*.apk



